# Generated by Django 5.0.4 on 2024-10-18 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Topic Category',
                'verbose_name_plural': 'Topic Categories',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=255, unique=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('topic_slug', models.SlugField(max_length=255, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('topic_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion_forum_app.topiccategory', verbose_name='Topic Categories')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='TopicAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('reply_date', models.DateField(auto_now_add=True)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion_forum_app.topic', verbose_name='Topic')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Topic Answer',
                'verbose_name_plural': 'Topic Answers',
            },
        ),
        migrations.CreateModel(
            name='AnswerUserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('UPVOTE', 'UPVOTE'), ('DOWNVOTE', 'DOWNVOTE'), ('NULL', 'NULL')], max_length=50, null=True)),
                ('reply_date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion_forum_app.topicanswer', verbose_name='Topic Answer')),
            ],
            options={
                'verbose_name': 'User Review On Answer',
                'verbose_name_plural': 'User Review On Answer',
            },
        ),
        migrations.CreateModel(
            name='AnswerReplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(blank=True, null=True)),
                ('reply_date', models.DateField(auto_now_add=True)),
                ('replied_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion_forum_app.answerreplies', verbose_name='replied to')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion_forum_app.topicanswer', verbose_name='Topic Answer')),
            ],
            options={
                'verbose_name': 'Answer Replies',
                'verbose_name_plural': 'Answer Replies',
            },
        ),
    ]
